from __future__ import annotations

import os


GITHUB_TOKEN_ENV = "GITHUB_TOKEN"
DEBUG_ENV = "OSS_ISSUE_SCOUT_DEBUG"
DEBUG_TRUE_VALUES = {"1", "true", "yes", "on"}

GITHUB_TOKEN = os.environ.get(GITHUB_TOKEN_ENV)
DEBUG_ENABLED = os.environ.get(DEBUG_ENV, "").strip().casefold() in DEBUG_TRUE_VALUES

GITHUB_API_BASE = "https://api.github.com"
GITHUB_GRAPHQL_URL = "https://api.github.com/graphql"
GITHUB_API_VERSION = "2026-03-10"

REQUEST_TIMEOUT_SECONDS = 20
REQUEST_RETRY_ATTEMPTS = 5
REQUEST_RETRY_DELAY_SECONDS = 1
TRANSIENT_HTTP_STATUS_CODES = {502, 503, 504}

DEFAULT_STARS_MIN = 100
MIN_REPO_OPEN_ISSUES = 3
MAX_GRAPHQL_SEARCH_PAGES = 20
MAX_REST_SEARCH_PAGES = 5
EXTENDED_SEARCH_MIN_RESULTS = 3
EXTENDED_SEARCH_PAGE_MULTIPLIER = 2
MAX_GRAPHQL_PAGE_SIZE = 25
MAX_REPO_WORKERS = 10
BACKFILL_PER_PAGE = 25

CANDIDATE_MULTIPLIER = 2
MIN_RECOMMENDED_SCORE = 85
MAX_CANDIDATE_LIMIT = 500
MAX_USER_LIMIT = MAX_CANDIDATE_LIMIT // CANDIDATE_MULTIPLIER
BACKFILL_REPO_LIMIT = 20
BACKFILL_PAGES_PER_REPO = 1
BACKFILL_DELAY_SECONDS = 1
